server:
  port: 8081

spring:
  application:
    name: doctor-service
  datasource:
    url: "jdbc:mysql://localhost:3306/DoctorHealthcareDB"
    username: root
    password: 123@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

