server:
  port: 8084

spring:
  application:
    name: appointment-service
  datasource:
    url: ""
    username: root
    password: 123@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true