server:
  port: 8083
#  servlet:
#    context-path: /patient

spring:
  application:
    name: patient-service
  datasource:
    url: "jdbc:mysql://localhost:3306/PatientHealthcareDB"
    username: root
    password: 123@123
  #    auto update db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

