server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      httpserver:
        websocket:
          enabled: true
      routes:
        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/doctors/**
          filters:
            - StripPrefix=0

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admins/**
          filters:
            - StripPrefix=0

        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patients/**
          filters:
            - StripPrefix=0

        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/appointments/**
          filters:
            - StripPrefix=0

        - id: realtime-service
          uri: lb://realtime-service
          predicates:
            - Path=/ws/**
          filters:
            - RemoveRequestHeader=Sec-WebSocket-Protocol
            - PreserveHostHeader
            - RewritePath=/ws(?<segment>/?.*), /ws${segment}



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
