server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/doctors/**
          filters:
            - StripPrefix=0

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admins/**
          filters:
            - StripPrefix=0

        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patients/**
          filters:
            - StripPrefix=0

        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/appointments/**
          filters:
            -StripPrefix=0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
