server:
  port: 8086

spring:
  application:
    name: payment-service
  datasource:
    url: "jdbc:mysql://localhost:3306/PaymentHealthcareDB"
    username: root
    password: 123@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/